version: '3.9'

networks:
  - servicebus_net

services:
  servicebus:
    image: nginx
    hostname: servicebus
    container_name: servicebus_loadbalancer
    ports:
      - "5670:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - servicebus_node_1
      - servicebus_node_2
      - servicebus_node_3  
    networks:
      servicebus_net:
          
  servicebus_node_1:
    image: rabbitmq:3.9
    command: bash -c "chmod 600 /var/lib/rabbitmq/.erlang.cookie && rabbitmq-server"
    container_name: servicebus_node_1
    hostname: servicebus_node_1
    volumes:
      - ./Node1/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
      servicebus_net:
        aliases:
          - servicebus_node_1
  
  servicebus_node_2:
    image: rabbitmq:3.9
    command: bash -c "chmod 600 /var/lib/rabbitmq/.erlang.cookie && rabbitmq-server"
    depends_on:
      - servicebus_node_1
    hostname: servicebus_node_2
    container_name: servicebus_node_2
    volumes:
      - ./Node2/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
      servicebus_net:
        aliases:
          - servicebus_node_2
      
  servicebus_node_3:
    image: rabbitmq:3.9
    command: bash -c "chmod 600 /var/lib/rabbitmq/.erlang.cookie && rabbitmq-server"
    depends_on:
      - servicebus_node_1
    hostname: servicebus_node_3
    container_name: servicebus_node_3
    volumes:
      - ./Node3/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
      servicebus_net:    
        aliases:
          - servicebus_node_3